# required metadata
sonar.projectKey=ZTS-Template-Editor-Frontend
sonar.projectName=ZTS Template Editor Frontend
# optional description
sonar.projectDescription=This project defines the ZTS Template Editor Frontend
# The value of the property must be the key of the language.
sonar.language=ts
# Encoding of the source code
sonar.sourceEncoding=UTF-8
# path to source directories (required)
sonar.sources=src
sonar.exclusions=src/tests/**/*, **/node_modules/**, **/dist/**, src/postcss.config.cjs, src/components/layout/*.vue, src/theme/**
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=coverage/sonar-report.xml
sonar.typescript.tsconfigPath=tsconfig.sonar.json
sonarjavascript.tsconfigSearchRecursive=false
sonar.tests=src/tests