worker_processes auto;
error_log /dev/stderr warn;
pid /tmp/nginx.pid;

events { worker_connections 1024; }

http {
  access_log /dev/stdout;

  client_body_temp_path /tmp/client_temp;
  proxy_temp_path       /tmp/proxy_temp;
  fastcgi_temp_path     /tmp/fastcgi_temp;
  uwsgi_temp_path       /tmp/uwsgi_temp;
  scgi_temp_path        /tmp/scgi_temp;

  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  server {
    listen 8080;
    server_name _;
    server_tokens off;
    absolute_redirect off;
    port_in_redirect off;

    root /usr/share/nginx/html;
    index index.html;

    ### avoid click-jacking
    add_header X-Frame-Options SAMEORIGIN;
    ### Enable the Cross-site scripting (XSS) filter
    add_header X-XSS-Protection "1; mode=block";
    
    # https://content-security-policy.com/examples/allow-inline-script/
    # keep unsafe-inline instead of nonce for script and styles loading purposes
    add_header Content-Security-Policy "base-uri 'self'; connect-src 'self'; frame-ancestors 'self'; frame-src 'self'; img-src 'self' data:; media-src 'self'; object-src 'none'; script-src 'self' ; style-src 'self' 'unsafe-inline'";
    add_header X-Content-Type-Options nosniff;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header Cross-Origin-Opener-Policy "same-origin";
    add_header Cache-Control "max-age=600";
    add_header Referrer-Policy "strict-origin-when-cross-origin";
    add_header Permissions-Policy "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()";
    ssl_session_tickets off;

    location = /config.js {
      default_type application/javascript;
      alias /tmp/config.js;

      add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
      expires -1;
    }

    location ~* \.(?:js|css|svg|png|jpg|jpeg|gif|woff2?)$ {
      expires 7d;
      add_header Cache-Control "public";
      try_files $uri =404;
    }

    location / {
      try_files $uri $uri/ /index.html;
    }

    location /healthz {
      return 200 'ok';
      add_header Content-Type text/plain;
    }
  }
}
